####Declare all instances information
instance_db:
  instance_names: ["servertest3"]
  machine_type: f1-micro
  count: 1
  boot_disk:
    image: centos-cloud/centos-7-v20190116
  zone: us-central1-a
  network_interfaces:
    network: vpctest
    subnet_name: dbzone
  script: "#!/bin/bash\nsudo touch /tmp/a.txt\nsudo yum install -y nginx\nsudo service nginx start"
  metadata:
    phucdh: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+K8iUKOFqb1+RTpnrjLZ4BYcbucqOW488EljBXErj5IJJma1Zr8gxBuB5BcJlbEc2JMtHRdpW7g9bpngMBnD8d0nYbWmdLwEjSdPiSM1bKhBbgxk1eIu8/rQWs1mesXNTku8BJggolVUsYf5Hh6pkQoUV7A54pIytAXRJ2QhXqoXnvxvESxG+x8KH2KgIa2yypI+sfilBhjSFtwNMMC5IsLcWq4clVFKdm0Rv63h+CwAyNjP52fBoBuOdJRSfyIjYOu6a7piJcopa4Zu8vwNjRAYzTvzazRFyRa9p0wYX/ogJahUGoSBEAaGKLgPCI1GdtOc+r00u2u8Ie2SKw1zaj97DM7bv/lAIcLnF3VPiBH65UtampC+EdOS2lHuOsfwdsyNssCABlp3xvVrqiBIE2TJnYTqLRQMy4QAbOqXRMeKwodyGVWyXebrCcdCMxQ69jSYAcecHRK6rMzHuxHH9taOl0MJS63d3MLmcj0XblxpJdhG5XOKnkQSDezbhgAR6rkp9caO5YGLOGIfdeW52ClwHD/ftdeElJWi8TAK+z2hyxkDeI9M88MPDVHhWAkf840mao3MC2JMS3E7tTfrwHZlGNm22HTDvT/2dxGoudiDHCYdPBvM8eBiXJ3yuzetuflBD1yynCQ5LpqEwy3Zoz+yeo5gbWkJY2/MjGAai0w== dinhhuuphuc.it@gmail.com"
instance_web:
  instance_names: ["servertestweb2"]
  machine_type: f1-micro
  count: 1
  boot_disk:
    image: centos-cloud/centos-7-v20190116
  zone: asia-southeast1-a
  network_interfaces:
    network: vpctest1
    subnet_name: webzone1
  script: "#!/bin/bash\nsudo touch /tmp/a.txt\nsudo yum install -y nginx\nsudo service nginx start"
  metadata:
    phucdh: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+K8iUKOFqb1+RTpnrjLZ4BYcbucqOW488EljBXErj5IJJma1Zr8gxBuB5BcJlbEc2JMtHRdpW7g9bpngMBnD8d0nYbWmdLwEjSdPiSM1bKhBbgxk1eIu8/rQWs1mesXNTku8BJggolVUsYf5Hh6pkQoUV7A54pIytAXRJ2QhXqoXnvxvESxG+x8KH2KgIa2yypI+sfilBhjSFtwNMMC5IsLcWq4clVFKdm0Rv63h+CwAyNjP52fBoBuOdJRSfyIjYOu6a7piJcopa4Zu8vwNjRAYzTvzazRFyRa9p0wYX/ogJahUGoSBEAaGKLgPCI1GdtOc+r00u2u8Ie2SKw1zaj97DM7bv/lAIcLnF3VPiBH65UtampC+EdOS2lHuOsfwdsyNssCABlp3xvVrqiBIE2TJnYTqLRQMy4QAbOqXRMeKwodyGVWyXebrCcdCMxQ69jSYAcecHRK6rMzHuxHH9taOl0MJS63d3MLmcj0XblxpJdhG5XOKnkQSDezbhgAR6rkp9caO5YGLOGIfdeW52ClwHD/ftdeElJWi8TAK+z2hyxkDeI9M88MPDVHhWAkf840mao3MC2JMS3E7tTfrwHZlGNm22HTDvT/2dxGoudiDHCYdPBvM8eBiXJ3yuzetuflBD1yynCQ5LpqEwy3Zoz+yeo5gbWkJY2/MjGAai0w== dinhhuuphuc.it@gmail.com"


